### ISSUE TITLE
Unexpected "is out-of-vocabulary" error

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/wembedder#15]
https://tools.wmflabs.org/wembedder/most-similar/Q11989#language=en
currently gives "Q11989 is out-of-vocabulary", and I do not see anything in
https://www.wikidata.org/wiki/Q11989
that would justify that.

**Comment by fnielsen** [comment]
There is just around 500,000 items in the Wembedder vocabulary. Due to memory restrictions of Toolforge it is difficult to make it larger.
