### ISSUE TITLE
Hosted API service on https://tools.wmflabs.org/wembedder not reachable

### ISSUE THREAD

**Issue by aschwarte10** [fnielsen/wembedder#16]
It appears that the hosted API service on https://tools.wmflabs.org/wembedder is not reachable.

Could you maybe investigate and let us know if and when the service can be available again?

**Comment by fnielsen** [comment]
Thanks for the reminder.

As a reminder to myself:
```bash
webservice stop
webservice --backend=kubernetes python3.7 shell
cd ~/www/python
python3.7 -m virtualenv -p /usr/bin/python3.7 venv3.7/
source venv3.7/bin/activate
pip install -r wembedder/requirements.txt
rm venv
ln -s venv3.7 venv
logout
webservice --backend=kubernetes -m 2G python3.7 restart
tail -f uwsgi.log 
```
Also added to https://github.com/fnielsen/wembedder/wiki .

I am closing it now, but reopen if there if it fails again. The system has recently been upgraded.
