### ISSUE TITLE
[Documentation] Folder structure

### ISSUE THREAD

**Issue by pasqLisena** [fnielsen/wembedder#7]
Hello! I would like to run your code for trying your wembedder.

I just want to ask you an explanation about the required files:
- what do you expect to have in the `wembedder_data/models` folder?
- what kind of file you expect instead as `cls` param in [model.py](https://github.com/fnielsen/wembedder/blob/master/wembedder/model.py#L16) ?

Thank you

**Comment by fnielsen** [comment]
Thanks for noting the missing information. I have added model information to the readme file at https://github.com/fnielsen/wembedder. On a Linux system you should create `wembedder_data/models` folders and unpack the linked zenodo files there. Let me know if you have any problems.

**Comment by fnielsen** [comment]
The `cls` input argument is not an ordinary input argument, - it is required as it is a class method. You would do `model = Model.load()` or `model = Model.load('your_directory')`

**Comment by pasqLisena** [comment]
Thank you a lot! I successfully run the application.
